//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(identifier: "com.adgvcxz.dribbble") ?? Bundle.main
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 1 color palettes.
  struct color {
    /// This `R.color.dribbble` struct is generated, and contains static references to 17 colors.
    struct dribbble {
      /// <span style='background-color: #000000; color: #FFFFFF; padding: 1px 3px;'>#000000</span> colorPrimaryStatusBarDark
      static let colorPrimaryStatusBarDark = Rswift.ColorResource(name: "colorPrimaryStatusBarDark", red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)
      /// <span style='background-color: #212121; color: #DEDEDE; padding: 1px 3px;'>#212121</span> colorPrimaryDark
      static let colorPrimaryDark = Rswift.ColorResource(name: "colorPrimaryDark", red: 0.1294117647, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      /// <span style='background-color: #212121; color: #DEDEDE; padding: 1px 3px;'>#212121</span> primaryTextColorLight
      static let primaryTextColorLight = Rswift.ColorResource(name: "primaryTextColorLight", red: 0.1294117647, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      /// <span style='background-color: #303030; color: #CFCFCF; padding: 1px 3px;'>#303030</span> mainBackgroundDark
      static let mainBackgroundDark = Rswift.ColorResource(name: "mainBackgroundDark", red: 0.1882352941, green: 0.1882352941, blue: 0.1882352941, alpha: 1.0)
      /// <span style='background-color: #393939; color: #C6C6C6; padding: 1px 3px;'>#393939</span> secondBackgroundDark
      static let secondBackgroundDark = Rswift.ColorResource(name: "secondBackgroundDark", red: 0.2235294118, green: 0.2235294118, blue: 0.2235294118, alpha: 1.0)
      /// <span style='background-color: #404040; color: #BFBFBF; padding: 1px 3px;'>#404040</span> dividerColorDark
      static let dividerColorDark = Rswift.ColorResource(name: "dividerColorDark", red: 0.2509803922, green: 0.2509803922, blue: 0.2509803922, alpha: 1.0)
      /// <span style='background-color: #424242; color: #BDBDBD; padding: 1px 3px;'>#424242</span> cardBackgroundDark
      static let cardBackgroundDark = Rswift.ColorResource(name: "cardBackgroundDark", red: 0.2588235294, green: 0.2588235294, blue: 0.2588235294, alpha: 1.0)
      /// <span style='background-color: #757575; color: #8A8A8A; padding: 1px 3px;'>#757575</span> secondTextColorLight
      static let secondTextColorLight = Rswift.ColorResource(name: "secondTextColorLight", red: 0.4588235294, green: 0.4588235294, blue: 0.4588235294, alpha: 1.0)
      /// <span style='background-color: #80CBC4; color: #7F343B; padding: 1px 3px;'>#80CBC4</span> colorAccent
      static let colorAccent = Rswift.ColorResource(name: "colorAccent", red: 0.5019607843, green: 0.7960784314, blue: 0.768627451, alpha: 1.0)
      /// <span style='background-color: #A0A0A0; color: #5F5F5F; padding: 1px 3px;'>#A0A0A0</span> secondTextColorDark
      static let secondTextColorDark = Rswift.ColorResource(name: "secondTextColorDark", red: 0.6274509804, green: 0.6274509804, blue: 0.6274509804, alpha: 1.0)
      /// <span style='background-color: #C2185B; color: #3DE7A4; padding: 1px 3px;'>#C2185B</span> colorPrimaryStatusBarLight
      static let colorPrimaryStatusBarLight = Rswift.ColorResource(name: "colorPrimaryStatusBarLight", red: 0.7607843137, green: 0.09411764706, blue: 0.3568627451, alpha: 1.0)
      /// <span style='background-color: #E91E63; color: #16E19C; padding: 1px 3px;'>#E91E63</span> colorPrimaryLight
      static let colorPrimaryLight = Rswift.ColorResource(name: "colorPrimaryLight", red: 0.9137254902, green: 0.1176470588, blue: 0.3882352941, alpha: 1.0)
      /// <span style='background-color: #EEEEEE; color: #111111; padding: 1px 3px;'>#EEEEEE</span> dividerColorLight
      static let dividerColorLight = Rswift.ColorResource(name: "dividerColorLight", red: 0.9333333333, green: 0.9333333333, blue: 0.9333333333, alpha: 1.0)
      /// <span style='background-color: #EEEEEE; color: #111111; padding: 1px 3px;'>#EEEEEE</span> primaryTextColorDark
      static let primaryTextColorDark = Rswift.ColorResource(name: "primaryTextColorDark", red: 0.9333333333, green: 0.9333333333, blue: 0.9333333333, alpha: 1.0)
      /// <span style='background-color: #F0F0F0; color: #0F0F0F; padding: 1px 3px;'>#F0F0F0</span> secondBackgroundLight
      static let secondBackgroundLight = Rswift.ColorResource(name: "secondBackgroundLight", red: 0.9411764706, green: 0.9411764706, blue: 0.9411764706, alpha: 1.0)
      /// <span style='background-color: #FAFAFA; color: #050505; padding: 1px 3px;'>#FAFAFA</span> mainBackgroundLight
      static let mainBackgroundLight = Rswift.ColorResource(name: "mainBackgroundLight", red: 0.9803921569, green: 0.9803921569, blue: 0.9803921569, alpha: 1.0)
      /// <span style='background-color: #FFFFFF; color: #000000; padding: 1px 3px;'>#FFFFFF</span> cardBackgroundLight
      static let cardBackgroundLight = Rswift.ColorResource(name: "cardBackgroundLight", red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
      
      /// <span style='background-color: #000000; color: #FFFFFF; padding: 1px 3px;'>#000000</span> colorPrimaryStatusBarDark
      /// 
      /// UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)
      static func colorPrimaryStatusBarDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0)
      }
      
      /// <span style='background-color: #212121; color: #DEDEDE; padding: 1px 3px;'>#212121</span> colorPrimaryDark
      /// 
      /// UIColor(red: 0.1294117647, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      static func colorPrimaryDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1294117647, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      }
      
      /// <span style='background-color: #212121; color: #DEDEDE; padding: 1px 3px;'>#212121</span> primaryTextColorLight
      /// 
      /// UIColor(red: 0.1294117647, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      static func primaryTextColorLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1294117647, green: 0.1294117647, blue: 0.1294117647, alpha: 1.0)
      }
      
      /// <span style='background-color: #303030; color: #CFCFCF; padding: 1px 3px;'>#303030</span> mainBackgroundDark
      /// 
      /// UIColor(red: 0.1882352941, green: 0.1882352941, blue: 0.1882352941, alpha: 1.0)
      static func mainBackgroundDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.1882352941, green: 0.1882352941, blue: 0.1882352941, alpha: 1.0)
      }
      
      /// <span style='background-color: #393939; color: #C6C6C6; padding: 1px 3px;'>#393939</span> secondBackgroundDark
      /// 
      /// UIColor(red: 0.2235294118, green: 0.2235294118, blue: 0.2235294118, alpha: 1.0)
      static func secondBackgroundDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.2235294118, green: 0.2235294118, blue: 0.2235294118, alpha: 1.0)
      }
      
      /// <span style='background-color: #404040; color: #BFBFBF; padding: 1px 3px;'>#404040</span> dividerColorDark
      /// 
      /// UIColor(red: 0.2509803922, green: 0.2509803922, blue: 0.2509803922, alpha: 1.0)
      static func dividerColorDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.2509803922, green: 0.2509803922, blue: 0.2509803922, alpha: 1.0)
      }
      
      /// <span style='background-color: #424242; color: #BDBDBD; padding: 1px 3px;'>#424242</span> cardBackgroundDark
      /// 
      /// UIColor(red: 0.2588235294, green: 0.2588235294, blue: 0.2588235294, alpha: 1.0)
      static func cardBackgroundDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.2588235294, green: 0.2588235294, blue: 0.2588235294, alpha: 1.0)
      }
      
      /// <span style='background-color: #757575; color: #8A8A8A; padding: 1px 3px;'>#757575</span> secondTextColorLight
      /// 
      /// UIColor(red: 0.4588235294, green: 0.4588235294, blue: 0.4588235294, alpha: 1.0)
      static func secondTextColorLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.4588235294, green: 0.4588235294, blue: 0.4588235294, alpha: 1.0)
      }
      
      /// <span style='background-color: #80CBC4; color: #7F343B; padding: 1px 3px;'>#80CBC4</span> colorAccent
      /// 
      /// UIColor(red: 0.5019607843, green: 0.7960784314, blue: 0.768627451, alpha: 1.0)
      static func colorAccent(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.5019607843, green: 0.7960784314, blue: 0.768627451, alpha: 1.0)
      }
      
      /// <span style='background-color: #A0A0A0; color: #5F5F5F; padding: 1px 3px;'>#A0A0A0</span> secondTextColorDark
      /// 
      /// UIColor(red: 0.6274509804, green: 0.6274509804, blue: 0.6274509804, alpha: 1.0)
      static func secondTextColorDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.6274509804, green: 0.6274509804, blue: 0.6274509804, alpha: 1.0)
      }
      
      /// <span style='background-color: #C2185B; color: #3DE7A4; padding: 1px 3px;'>#C2185B</span> colorPrimaryStatusBarLight
      /// 
      /// UIColor(red: 0.7607843137, green: 0.09411764706, blue: 0.3568627451, alpha: 1.0)
      static func colorPrimaryStatusBarLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.7607843137, green: 0.09411764706, blue: 0.3568627451, alpha: 1.0)
      }
      
      /// <span style='background-color: #E91E63; color: #16E19C; padding: 1px 3px;'>#E91E63</span> colorPrimaryLight
      /// 
      /// UIColor(red: 0.9137254902, green: 0.1176470588, blue: 0.3882352941, alpha: 1.0)
      static func colorPrimaryLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9137254902, green: 0.1176470588, blue: 0.3882352941, alpha: 1.0)
      }
      
      /// <span style='background-color: #EEEEEE; color: #111111; padding: 1px 3px;'>#EEEEEE</span> dividerColorLight
      /// 
      /// UIColor(red: 0.9333333333, green: 0.9333333333, blue: 0.9333333333, alpha: 1.0)
      static func dividerColorLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9333333333, green: 0.9333333333, blue: 0.9333333333, alpha: 1.0)
      }
      
      /// <span style='background-color: #EEEEEE; color: #111111; padding: 1px 3px;'>#EEEEEE</span> primaryTextColorDark
      /// 
      /// UIColor(red: 0.9333333333, green: 0.9333333333, blue: 0.9333333333, alpha: 1.0)
      static func primaryTextColorDark(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9333333333, green: 0.9333333333, blue: 0.9333333333, alpha: 1.0)
      }
      
      /// <span style='background-color: #F0F0F0; color: #0F0F0F; padding: 1px 3px;'>#F0F0F0</span> secondBackgroundLight
      /// 
      /// UIColor(red: 0.9411764706, green: 0.9411764706, blue: 0.9411764706, alpha: 1.0)
      static func secondBackgroundLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9411764706, green: 0.9411764706, blue: 0.9411764706, alpha: 1.0)
      }
      
      /// <span style='background-color: #FAFAFA; color: #050505; padding: 1px 3px;'>#FAFAFA</span> mainBackgroundLight
      /// 
      /// UIColor(red: 0.9803921569, green: 0.9803921569, blue: 0.9803921569, alpha: 1.0)
      static func mainBackgroundLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 0.9803921569, green: 0.9803921569, blue: 0.9803921569, alpha: 1.0)
      }
      
      /// <span style='background-color: #FFFFFF; color: #000000; padding: 1px 3px;'>#FFFFFF</span> cardBackgroundLight
      /// 
      /// UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
      static func cardBackgroundLight(_: Void = ()) -> UIKit.UIColor {
        return UIKit.UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `dribbble.clr`.
    static let dribbbleClr = Rswift.FileResource(bundle: R.hostingBundle, name: "dribbble", pathExtension: "clr")
    
    /// `bundle.url(forResource: "dribbble", withExtension: "clr")`
    static func dribbbleClr(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.dribbbleClr
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}